---
# tasks file for roles/inv_report
- name: create HTML report
  ansible.builtin.template:
    src: "{{ table_type }}.j2"
    dest: "{{ file_path }}"
    mode: 0644
    lstrip_blocks: True
  delegate_to: localhost
  run_once: true
